name: Replace zhukov with hasnainkk-07

on:
  push:
    branches:
      - master

jobs:
  replace-text:
    runs-on: ubuntu-latest
    permissions:  # Specify only the permissions you need
      contents: write  # This allows the workflow to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace text in all files
        run: |
          find . -type f -exec sed -i 's/zhukov/hasnainkk-07/g' {} +

      - name: Commit changes
        run: |
          git config --local user.name "hasnainkk-07"
          git config --local user.email "hasnainkk98075@gmail.com"
          git add .
          git commit -m "Initial commit" || echo "No changes to commit"

      - name: Push changes
        run: git push
