name: Replace zhukov with hasnainkk-07

on:
  push:
    branches:
      - master

jobs:
  replace-text:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This allows the workflow to push changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace text in all files
        run: |
          find . -type f -exec sed -i 's/zhukov/hasnainkk-07/g' {} +

      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Replace zhukov with hasnainkk-07" || echo "No changes to commit"

      - name: Push changes
        run: git push
