name: Replace Zhukov with hasnainkk-07

on:
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        # Set the global commit username and email
        git config --global user.name "hasnainkk-07"
        git config --global user.email "hasnainkk98075@gmail.com"

    - name: Replace Zhukov with hasnainkk-07
      run: |
        # Replace all occurrences of 'Zhukov' with 'hasnainkk-07'
        find . -type f -exec sed -i 's/Zhukov/hasnainkk-07/g' {} +

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Initial commit"
        git push
