name: Replace Zhukov with hasnainkk-07

on:
  push:
    branches:
      - master  # Trigger this workflow when there's a push to the main branch
  workflow_dispatch:  # Allows for manual triggering of the workflow via GitHub UI
  schedule:
    - cron: "0 0 * * *"  # This will run the action daily at midnight UTC

jobs:
  replace:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Replace Zhukov with hasnainkk-07
      run: |
        # Replace all occurrences of 'Zhukov' with 'hasnainkk-07'
        find . -type f -exec sed -i 's/Zhukov/hasnainkk-07/g' {} +

    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Initial commit"
        git push origin master
