name: Replace zhukov with hasnainkk-07

on:
  push:
    branches:
      - master

permissions:
  contents: write
  workflows: write  # Add this line

jobs:
  replace-text:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Replace text in all files
        run: |
          find . -type f -exec sed -i 's/zhukov/hasnainkk-07/g' {} +

      - name: Commit changes
        run: |
          git config --local user.name "hasnainkk-07"
          git config --local user.email "hasnainkk98075@gmail.com"
          git add .
          git commit -m "Initial commit" || echo "No changes to commit"

      - name: Push changes
        run: git push
